### ISSUE TITLE
yaml -> environment variables

### ISSUE THREAD

**Issue by osterbit** [qri-recipes/overview#2]
@b5, just want to clarify:
- I execute `docker run`
- parameters specified in the yaml file are exported as environment variables
- python/shell/golang script executes in an environment with those environment variables set

**Comment by osterbit** [comment]
so you can set environment variables easily in python but only child processes inherit that environment it seems.  the simplest way to get around that (that I can think of right now) would be to append a shell script text file with lines of `export {varname}={varval}` which then makes me think--why don't we just put the params in a shell script and call `source params.sh` at the beginning?

**Comment by b5** [comment]
Ok, after [some reading](https://docs.docker.com/compose/compose-file/#env_file) we should change raname `config.yml` to `config.env` and store configuration values in ".env format". Ok, .env isn't really a format, but this is the gist:

```sh
# .env files can have comments. Yay!
# configure like this:
RACK_ENV=development
```

The trick is in the `docker run` bit. When we eventually move recipes into qri as transformations qri will (theoretically) read configuration from somewhere (it'll probably be stored in the transformation definition of the dataset, and inject those configuration values into the container execution like so:

`docker run . --env-file=config.env`

which'll auto-load the configuration. This also means we can use off-the-shelf .env file readers in various languages. Mind PR'ing in this info? If not I can get to it later in the week
